# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\what_trash_project\git\gui\basic2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setPointSize(2)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.trash_menu = QtWidgets.QLabel(self.centralwidget)
        self.trash_menu.setGeometry(QtCore.QRect(480, 240, 970, 721))
        font = QtGui.QFont()
        font.setFamily("배달의민족 도현")
        font.setPointSize(90)
        self.trash_menu.setFont(font)
        self.trash_menu.setMouseTracking(True)
        self.trash_menu.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.trash_menu.setTextFormat(QtCore.Qt.AutoText)
        self.trash_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_menu.setObjectName("trash_menu")
        self.trash_title = QtWidgets.QLabel(self.centralwidget)
        self.trash_title.setGeometry(QtCore.QRect(550, 130, 800, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.trash_title.setFont(font)
        self.trash_title.setStyleSheet("color : rgb(217,217,217)\n"
"")
        self.trash_title.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_title.setObjectName("trash_title")
        self.trash_day = QtWidgets.QLabel(self.centralwidget)
        self.trash_day.setGeometry(QtCore.QRect(1090, 1030, 811, 41))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.trash_day.setFont(font)
        self.trash_day.setStyleSheet("color : rgb(191,191,191)\n"
"")
        self.trash_day.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trash_day.setObjectName("trash_day")
        self.trash_school = QtWidgets.QLabel(self.centralwidget)
        self.trash_school.setGeometry(QtCore.QRect(1100, 980, 801, 41))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.trash_school.setFont(font)
        self.trash_school.setStyleSheet("color : rgb(191,191,191)\n"
"")
        self.trash_school.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trash_school.setObjectName("trash_school")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-2, -21, 506, 1121))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("background-color: rgb(0,176,240);")
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.set_main = QtWidgets.QWidget()
        self.set_main.setObjectName("set_main")
        self.trash_set_title = QtWidgets.QLabel(self.set_main)
        self.trash_set_title.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.trash_set_title.setFont(font)
        self.trash_set_title.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.trash_set_title.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_set_title.setObjectName("trash_set_title")
        self.trash_con = QtWidgets.QLabel(self.set_main)
        self.trash_con.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con.setFont(font)
        self.trash_con.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con.setObjectName("trash_con")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.set_main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 501, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.set_main_l = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.set_main_l.setContentsMargins(0, 0, 0, 0)
        self.set_main_l.setSpacing(0)
        self.set_main_l.setObjectName("set_main_l")
        self.set_main_1 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.set_main_1.setStyleSheet(");")
        self.set_main_1.setObjectName("set_main_1")
        self.label_2 = QtWidgets.QLabel(self.set_main_1)
        self.label_2.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("image/college-graduation.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.set_main_1)
        self.label_3.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : rgb(255,255,255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.set_main_1)
        self.label_4.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.set_main_l.addWidget(self.set_main_1)
        self.set_main_2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.set_main_2.setObjectName("set_main_2")
        self.label_16 = QtWidgets.QLabel(self.set_main_2)
        self.label_16.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.set_main_2)
        self.label_17.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color : rgb(255,255,255)")
        self.label_17.setObjectName("label_17")
        self.label_22 = QtWidgets.QLabel(self.set_main_2)
        self.label_22.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("image/clock.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.set_main_l.addWidget(self.set_main_2)
        self.set_main_3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.set_main_3.setObjectName("set_main_3")
        self.label_21 = QtWidgets.QLabel(self.set_main_3)
        self.label_21.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color : rgb(255,255,255)")
        self.label_21.setObjectName("label_21")
        self.label_20 = QtWidgets.QLabel(self.set_main_3)
        self.label_20.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(self.set_main_3)
        self.label_23.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("image/trash.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.set_main_l.addWidget(self.set_main_3)
        self.set_main_4 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.set_main_4.setObjectName("set_main_4")
        self.label_55 = QtWidgets.QLabel(self.set_main_4)
        self.label_55.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color : rgb(255,255,255)")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.set_main_4)
        self.label_56.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.set_main_4)
        self.label_57.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap("image/list.png"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.set_main_l.addWidget(self.set_main_4)
        self.tabWidget.addTab(self.set_main, "")
        self.set_kit_1_1 = QtWidgets.QWidget()
        self.set_kit_1_1.setObjectName("set_kit_1_1")
        self.set_kit_1_title = QtWidgets.QLabel(self.set_kit_1_1)
        self.set_kit_1_title.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.set_kit_1_title.setFont(font)
        self.set_kit_1_title.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.set_kit_1_title.setAlignment(QtCore.Qt.AlignCenter)
        self.set_kit_1_title.setObjectName("set_kit_1_title")
        self.trash_con_3 = QtWidgets.QLabel(self.set_kit_1_1)
        self.trash_con_3.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con_3.setFont(font)
        self.trash_con_3.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_3.setObjectName("trash_con_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.set_kit_1_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 80, 501, 891))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.set_kit_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.set_kit_1.setContentsMargins(0, 0, 0, 0)
        self.set_kit_1.setSpacing(0)
        self.set_kit_1.setObjectName("set_kit_1")
        self._1_1 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_1.setObjectName("_1_1")
        self.l1 = QtWidgets.QLabel(self._1_1)
        self.l1.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l1.setObjectName("l1")
        self.c_1 = QtWidgets.QLabel(self._1_1)
        self.c_1.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_1.setText("")
        self.c_1.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_1.setScaledContents(True)
        self.c_1.setObjectName("c_1")
        self.set_kit_1.addWidget(self._1_1)
        self._1_2 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_2.setObjectName("_1_2")
        self.l2 = QtWidgets.QLabel(self._1_2)
        self.l2.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l2.setFont(font)
        self.l2.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l2.setObjectName("l2")
        self.c_2 = QtWidgets.QLabel(self._1_2)
        self.c_2.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_2.setText("")
        self.c_2.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_2.setScaledContents(True)
        self.c_2.setObjectName("c_2")
        self.set_kit_1.addWidget(self._1_2)
        self._1_3 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_3.setObjectName("_1_3")
        self.l3 = QtWidgets.QLabel(self._1_3)
        self.l3.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l3.setFont(font)
        self.l3.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l3.setObjectName("l3")
        self.c_3 = QtWidgets.QLabel(self._1_3)
        self.c_3.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_3.setText("")
        self.c_3.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_3.setScaledContents(True)
        self.c_3.setObjectName("c_3")
        self.set_kit_1.addWidget(self._1_3)
        self._1_4 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_4.setObjectName("_1_4")
        self.l4 = QtWidgets.QLabel(self._1_4)
        self.l4.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l4.setFont(font)
        self.l4.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l4.setObjectName("l4")
        self.c_4 = QtWidgets.QLabel(self._1_4)
        self.c_4.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_4.setText("")
        self.c_4.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_4.setScaledContents(True)
        self.c_4.setObjectName("c_4")
        self.set_kit_1.addWidget(self._1_4)
        self._1_5 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_5.setObjectName("_1_5")
        self.l5 = QtWidgets.QLabel(self._1_5)
        self.l5.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l5.setFont(font)
        self.l5.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l5.setObjectName("l5")
        self.c_5 = QtWidgets.QLabel(self._1_5)
        self.c_5.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_5.setText("")
        self.c_5.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_5.setScaledContents(True)
        self.c_5.setObjectName("c_5")
        self.set_kit_1.addWidget(self._1_5)
        self._1_6 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_6.setObjectName("_1_6")
        self.l6 = QtWidgets.QLabel(self._1_6)
        self.l6.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l6.setFont(font)
        self.l6.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l6.setObjectName("l6")
        self.c_6 = QtWidgets.QLabel(self._1_6)
        self.c_6.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_6.setText("")
        self.c_6.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_6.setScaledContents(True)
        self.c_6.setObjectName("c_6")
        self.set_kit_1.addWidget(self._1_6)
        self._1_7 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_7.setObjectName("_1_7")
        self.l7 = QtWidgets.QLabel(self._1_7)
        self.l7.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l7.setFont(font)
        self.l7.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l7.setObjectName("l7")
        self.c_7 = QtWidgets.QLabel(self._1_7)
        self.c_7.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_7.setText("")
        self.c_7.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_7.setScaledContents(True)
        self.c_7.setObjectName("c_7")
        self.set_kit_1.addWidget(self._1_7)
        self._1_8 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_8.setObjectName("_1_8")
        self.l8 = QtWidgets.QLabel(self._1_8)
        self.l8.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l8.setFont(font)
        self.l8.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l8.setObjectName("l8")
        self.c_8 = QtWidgets.QLabel(self._1_8)
        self.c_8.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_8.setText("")
        self.c_8.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_8.setScaledContents(True)
        self.c_8.setObjectName("c_8")
        self.set_kit_1.addWidget(self._1_8)
        self._1_9 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_9.setObjectName("_1_9")
        self.l9 = QtWidgets.QLabel(self._1_9)
        self.l9.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l9.setFont(font)
        self.l9.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l9.setObjectName("l9")
        self.c_9 = QtWidgets.QLabel(self._1_9)
        self.c_9.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_9.setText("")
        self.c_9.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_9.setScaledContents(True)
        self.c_9.setObjectName("c_9")
        self.set_kit_1.addWidget(self._1_9)
        self._1_10 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_10.setObjectName("_1_10")
        self.l10 = QtWidgets.QLabel(self._1_10)
        self.l10.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l10.setFont(font)
        self.l10.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l10.setObjectName("l10")
        self.c_10 = QtWidgets.QLabel(self._1_10)
        self.c_10.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_10.setText("")
        self.c_10.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_10.setScaledContents(True)
        self.c_10.setObjectName("c_10")
        self.set_kit_1.addWidget(self._1_10)
        self._1_11 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_11.setObjectName("_1_11")
        self.l11 = QtWidgets.QLabel(self._1_11)
        self.l11.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l11.setFont(font)
        self.l11.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l11.setObjectName("l11")
        self.c_11 = QtWidgets.QLabel(self._1_11)
        self.c_11.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_11.setText("")
        self.c_11.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_11.setScaledContents(True)
        self.c_11.setObjectName("c_11")
        self.set_kit_1.addWidget(self._1_11)
        self._1_12 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_12.setObjectName("_1_12")
        self.l12 = QtWidgets.QLabel(self._1_12)
        self.l12.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l12.setFont(font)
        self.l12.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l12.setObjectName("l12")
        self.c_12 = QtWidgets.QLabel(self._1_12)
        self.c_12.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_12.setText("")
        self.c_12.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_12.setScaledContents(True)
        self.c_12.setObjectName("c_12")
        self.set_kit_1.addWidget(self._1_12)
        self._1_13 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_13.setObjectName("_1_13")
        self.l13 = QtWidgets.QLabel(self._1_13)
        self.l13.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l13.setFont(font)
        self.l13.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l13.setObjectName("l13")
        self.c_13 = QtWidgets.QLabel(self._1_13)
        self.c_13.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_13.setText("")
        self.c_13.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_13.setScaledContents(True)
        self.c_13.setObjectName("c_13")
        self.set_kit_1.addWidget(self._1_13)
        self._1_14 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_14.setObjectName("_1_14")
        self.l14 = QtWidgets.QLabel(self._1_14)
        self.l14.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l14.setFont(font)
        self.l14.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l14.setObjectName("l14")
        self.c_14 = QtWidgets.QLabel(self._1_14)
        self.c_14.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_14.setText("")
        self.c_14.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_14.setScaledContents(True)
        self.c_14.setObjectName("c_14")
        self.set_kit_1.addWidget(self._1_14)
        self._1_15 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self._1_15.setObjectName("_1_15")
        self.l15 = QtWidgets.QLabel(self._1_15)
        self.l15.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l15.setFont(font)
        self.l15.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l15.setObjectName("l15")
        self.c_15 = QtWidgets.QLabel(self._1_15)
        self.c_15.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.c_15.setText("")
        self.c_15.setPixmap(QtGui.QPixmap("image/right.png"))
        self.c_15.setScaledContents(True)
        self.c_15.setObjectName("c_15")
        self.set_kit_1.addWidget(self._1_15)
        self.tabWidget.addTab(self.set_kit_1_1, "")
        self.set_sc_2_2 = QtWidgets.QWidget()
        self.set_sc_2_2.setObjectName("set_sc_2_2")
        self.set_kit_2_title = QtWidgets.QLabel(self.set_sc_2_2)
        self.set_kit_2_title.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.set_kit_2_title.setFont(font)
        self.set_kit_2_title.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.set_kit_2_title.setAlignment(QtCore.Qt.AlignCenter)
        self.set_kit_2_title.setObjectName("set_kit_2_title")
        self.trash_con_4 = QtWidgets.QLabel(self.set_sc_2_2)
        self.trash_con_4.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con_4.setFont(font)
        self.trash_con_4.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_4.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_4.setObjectName("trash_con_4")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.set_sc_2_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 120, 501, 831))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.set_kit_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.set_kit_2.setContentsMargins(0, 0, 0, 0)
        self.set_kit_2.setSpacing(0)
        self.set_kit_2.setObjectName("set_kit_2")
        self._2_1 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_1.setObjectName("_2_1")
        self.l21 = QtWidgets.QLabel(self._2_1)
        self.l21.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l21.setFont(font)
        self.l21.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l21.setObjectName("l21")
        self.label_47 = QtWidgets.QLabel(self._2_1)
        self.label_47.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_47.setScaledContents(True)
        self.label_47.setObjectName("label_47")
        self.set_kit_2.addWidget(self._2_1)
        self._2_2 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_2.setObjectName("_2_2")
        self.l22 = QtWidgets.QLabel(self._2_2)
        self.l22.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l22.setFont(font)
        self.l22.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l22.setObjectName("l22")
        self.label_88 = QtWidgets.QLabel(self._2_2)
        self.label_88.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_88.setText("")
        self.label_88.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_88.setScaledContents(True)
        self.label_88.setObjectName("label_88")
        self.set_kit_2.addWidget(self._2_2)
        self._2_3 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_3.setObjectName("_2_3")
        self.l23 = QtWidgets.QLabel(self._2_3)
        self.l23.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l23.setFont(font)
        self.l23.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l23.setObjectName("l23")
        self.label_90 = QtWidgets.QLabel(self._2_3)
        self.label_90.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_90.setText("")
        self.label_90.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_90.setScaledContents(True)
        self.label_90.setObjectName("label_90")
        self.set_kit_2.addWidget(self._2_3)
        self._2_4 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_4.setObjectName("_2_4")
        self.l24 = QtWidgets.QLabel(self._2_4)
        self.l24.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l24.setFont(font)
        self.l24.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l24.setObjectName("l24")
        self.label_92 = QtWidgets.QLabel(self._2_4)
        self.label_92.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_92.setText("")
        self.label_92.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_92.setScaledContents(True)
        self.label_92.setObjectName("label_92")
        self.set_kit_2.addWidget(self._2_4)
        self._2_5 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_5.setObjectName("_2_5")
        self.l25 = QtWidgets.QLabel(self._2_5)
        self.l25.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l25.setFont(font)
        self.l25.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l25.setObjectName("l25")
        self.label_94 = QtWidgets.QLabel(self._2_5)
        self.label_94.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_94.setText("")
        self.label_94.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_94.setScaledContents(True)
        self.label_94.setObjectName("label_94")
        self.set_kit_2.addWidget(self._2_5)
        self._2_6 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_6.setObjectName("_2_6")
        self.l26 = QtWidgets.QLabel(self._2_6)
        self.l26.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l26.setFont(font)
        self.l26.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l26.setObjectName("l26")
        self.label_96 = QtWidgets.QLabel(self._2_6)
        self.label_96.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_96.setText("")
        self.label_96.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_96.setScaledContents(True)
        self.label_96.setObjectName("label_96")
        self.set_kit_2.addWidget(self._2_6)
        self._2_7 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_7.setObjectName("_2_7")
        self.l27 = QtWidgets.QLabel(self._2_7)
        self.l27.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l27.setFont(font)
        self.l27.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l27.setObjectName("l27")
        self.label_98 = QtWidgets.QLabel(self._2_7)
        self.label_98.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_98.setText("")
        self.label_98.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_98.setScaledContents(True)
        self.label_98.setObjectName("label_98")
        self.set_kit_2.addWidget(self._2_7)
        self._2_8 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_8.setObjectName("_2_8")
        self.l28 = QtWidgets.QLabel(self._2_8)
        self.l28.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l28.setFont(font)
        self.l28.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l28.setObjectName("l28")
        self.asd = QtWidgets.QLabel(self._2_8)
        self.asd.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.asd.setText("")
        self.asd.setPixmap(QtGui.QPixmap("image/right.png"))
        self.asd.setScaledContents(True)
        self.asd.setObjectName("asd")
        self.set_kit_2.addWidget(self._2_8)
        self._2_9 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_9.setObjectName("_2_9")
        self.l29 = QtWidgets.QLabel(self._2_9)
        self.l29.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l29.setFont(font)
        self.l29.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l29.setObjectName("l29")
        self.label_102 = QtWidgets.QLabel(self._2_9)
        self.label_102.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_102.setText("")
        self.label_102.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_102.setScaledContents(True)
        self.label_102.setObjectName("label_102")
        self.set_kit_2.addWidget(self._2_9)
        self._2_10 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_10.setObjectName("_2_10")
        self.l210 = QtWidgets.QLabel(self._2_10)
        self.l210.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l210.setFont(font)
        self.l210.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l210.setObjectName("l210")
        self.label_104 = QtWidgets.QLabel(self._2_10)
        self.label_104.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_104.setText("")
        self.label_104.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_104.setScaledContents(True)
        self.label_104.setObjectName("label_104")
        self.set_kit_2.addWidget(self._2_10)
        self._2_11 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_11.setObjectName("_2_11")
        self.l211 = QtWidgets.QLabel(self._2_11)
        self.l211.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l211.setFont(font)
        self.l211.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l211.setObjectName("l211")
        self.label_106 = QtWidgets.QLabel(self._2_11)
        self.label_106.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_106.setText("")
        self.label_106.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_106.setScaledContents(True)
        self.label_106.setObjectName("label_106")
        self.set_kit_2.addWidget(self._2_11)
        self._2_12 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_12.setObjectName("_2_12")
        self.l212 = QtWidgets.QLabel(self._2_12)
        self.l212.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l212.setFont(font)
        self.l212.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l212.setObjectName("l212")
        self.label_108 = QtWidgets.QLabel(self._2_12)
        self.label_108.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_108.setText("")
        self.label_108.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_108.setScaledContents(True)
        self.label_108.setObjectName("label_108")
        self.set_kit_2.addWidget(self._2_12)
        self._2_13 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_13.setObjectName("_2_13")
        self.l213 = QtWidgets.QLabel(self._2_13)
        self.l213.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l213.setFont(font)
        self.l213.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l213.setObjectName("l213")
        self.label_110 = QtWidgets.QLabel(self._2_13)
        self.label_110.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_110.setText("")
        self.label_110.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_110.setScaledContents(True)
        self.label_110.setObjectName("label_110")
        self.set_kit_2.addWidget(self._2_13)
        self._2_14 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self._2_14.setObjectName("_2_14")
        self.l214 = QtWidgets.QLabel(self._2_14)
        self.l214.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l214.setFont(font)
        self.l214.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l214.setObjectName("l214")
        self.label_112 = QtWidgets.QLabel(self._2_14)
        self.label_112.setGeometry(QtCore.QRect(460, 17, 15, 25))
        self.label_112.setText("")
        self.label_112.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_112.setScaledContents(True)
        self.label_112.setObjectName("label_112")
        self.set_kit_2.addWidget(self._2_14)
        self.trash_con_6 = QtWidgets.QLabel(self.set_sc_2_2)
        self.trash_con_6.setGeometry(QtCore.QRect(0, 950, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(18)
        self.trash_con_6.setFont(font)
        self.trash_con_6.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_6.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_6.setObjectName("trash_con_6")
        self.trash_con_7 = QtWidgets.QLabel(self.set_sc_2_2)
        self.trash_con_7.setGeometry(QtCore.QRect(0, 90, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(18)
        self.trash_con_7.setFont(font)
        self.trash_con_7.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_7.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_7.setObjectName("trash_con_7")
        self.tabWidget.addTab(self.set_sc_2_2, "")
        self.set_eat_time = QtWidgets.QWidget()
        self.set_eat_time.setObjectName("set_eat_time")
        self.trash_set_title_8 = QtWidgets.QLabel(self.set_eat_time)
        self.trash_set_title_8.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.trash_set_title_8.setFont(font)
        self.trash_set_title_8.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.trash_set_title_8.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_set_title_8.setObjectName("trash_set_title_8")
        self.trash_con_8 = QtWidgets.QLabel(self.set_eat_time)
        self.trash_con_8.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con_8.setFont(font)
        self.trash_con_8.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_8.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_8.setObjectName("trash_con_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.set_eat_time)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 80, 501, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.set_eat_l = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.set_eat_l.setContentsMargins(0, 0, 0, 0)
        self.set_eat_l.setSpacing(0)
        self.set_eat_l.setObjectName("set_eat_l")
        self.set_eat_1 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.set_eat_1.setStyleSheet("background-color: rgb(0,161,218);")
        self.set_eat_1.setObjectName("set_eat_1")
        self.label_14 = QtWidgets.QLabel(self.set_eat_1)
        self.label_14.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("image/bread (1).png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.set_eat_1)
        self.label_15.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color : rgb(255,255,255)")
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.set_eat_1)
        self.label_18.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.set_eat_l.addWidget(self.set_eat_1)
        self.set_eat_2 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.set_eat_2.setObjectName("set_eat_2")
        self.label_19 = QtWidgets.QLabel(self.set_eat_2)
        self.label_19.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(self.set_eat_2)
        self.label_24.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color : rgb(255,255,255)")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.set_eat_2)
        self.label_25.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("../../기획서/이미지/rice-bowl-with-chopsticks.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.set_eat_l.addWidget(self.set_eat_2)
        self.set_eat_3 = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.set_eat_3.setObjectName("set_eat_3")
        self.label_26 = QtWidgets.QLabel(self.set_eat_3)
        self.label_26.setGeometry(QtCore.QRect(120, 0, 281, 101))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(24)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color : rgb(255,255,255)")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.set_eat_3)
        self.label_27.setGeometry(QtCore.QRect(440, 33, 18, 31))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("image/right.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.set_eat_3)
        self.label_28.setGeometry(QtCore.QRect(30, 25, 50, 50))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("../../기획서/이미지/dinner.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.set_eat_l.addWidget(self.set_eat_3)
        self.tabWidget.addTab(self.set_eat_time, "")
        self.set_time_change = QtWidgets.QWidget()
        self.set_time_change.setObjectName("set_time_change")
        self.trash_con_10 = QtWidgets.QLabel(self.set_time_change)
        self.trash_con_10.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con_10.setFont(font)
        self.trash_con_10.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_10.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_10.setObjectName("trash_con_10")
        self.set_time_change_title = QtWidgets.QLabel(self.set_time_change)
        self.set_time_change_title.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.set_time_change_title.setFont(font)
        self.set_time_change_title.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.set_time_change_title.setAlignment(QtCore.Qt.AlignCenter)
        self.set_time_change_title.setObjectName("set_time_change_title")
        self.label_5 = QtWidgets.QLabel(self.set_time_change)
        self.label_5.setGeometry(QtCore.QRect(-5, 80, 511, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("image/time.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.set_time_change_value = QtWidgets.QLabel(self.set_time_change)
        self.set_time_change_value.setGeometry(QtCore.QRect(90, 140, 321, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(26)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.set_time_change_value.setFont(font)
        self.set_time_change_value.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,161,218);")
        self.set_time_change_value.setAlignment(QtCore.Qt.AlignCenter)
        self.set_time_change_value.setObjectName("set_time_change_value")
        self.trash_con_11 = QtWidgets.QLabel(self.set_time_change)
        self.trash_con_11.setGeometry(QtCore.QRect(10, 280, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(18)
        self.trash_con_11.setFont(font)
        self.trash_con_11.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.trash_con_11.setObjectName("trash_con_11")
        self.tabWidget.addTab(self.set_time_change, "")
        self.set_trash_change = QtWidgets.QWidget()
        self.set_trash_change.setObjectName("set_trash_change")
        self.trash_set_title_5 = QtWidgets.QLabel(self.set_trash_change)
        self.trash_set_title_5.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.trash_set_title_5.setFont(font)
        self.trash_set_title_5.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.trash_set_title_5.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_set_title_5.setObjectName("trash_set_title_5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.set_trash_change)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 80, 501, 891))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._3_1 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_1.setObjectName("_3_1")
        self.l_3_1 = QtWidgets.QLabel(self._3_1)
        self.l_3_1.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_1.setFont(font)
        self.l_3_1.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_1.setObjectName("l_3_1")
        self.l2_3_1 = QtWidgets.QLabel(self._3_1)
        self.l2_3_1.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_1.setText("")
        self.l2_3_1.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_1.setScaledContents(True)
        self.l2_3_1.setObjectName("l2_3_1")
        self.verticalLayout_2.addWidget(self._3_1)
        self._3_2 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_2.setObjectName("_3_2")
        self.l_3_2 = QtWidgets.QLabel(self._3_2)
        self.l_3_2.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_2.setFont(font)
        self.l_3_2.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_2.setObjectName("l_3_2")
        self.l2_3_2 = QtWidgets.QLabel(self._3_2)
        self.l2_3_2.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_2.setText("")
        self.l2_3_2.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_2.setScaledContents(True)
        self.l2_3_2.setObjectName("l2_3_2")
        self.verticalLayout_2.addWidget(self._3_2)
        self._3_3 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_3.setObjectName("_3_3")
        self.l_3_3 = QtWidgets.QLabel(self._3_3)
        self.l_3_3.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_3.setFont(font)
        self.l_3_3.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_3.setObjectName("l_3_3")
        self.l2_3_3 = QtWidgets.QLabel(self._3_3)
        self.l2_3_3.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_3.setText("")
        self.l2_3_3.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_3.setScaledContents(True)
        self.l2_3_3.setObjectName("l2_3_3")
        self.verticalLayout_2.addWidget(self._3_3)
        self._3_4 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_4.setObjectName("_3_4")
        self.l_3_4 = QtWidgets.QLabel(self._3_4)
        self.l_3_4.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_4.setFont(font)
        self.l_3_4.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_4.setObjectName("l_3_4")
        self.l2_3_4 = QtWidgets.QLabel(self._3_4)
        self.l2_3_4.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_4.setText("")
        self.l2_3_4.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_4.setScaledContents(True)
        self.l2_3_4.setObjectName("l2_3_4")
        self.verticalLayout_2.addWidget(self._3_4)
        self._3_5 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_5.setObjectName("_3_5")
        self.l_3_5 = QtWidgets.QLabel(self._3_5)
        self.l_3_5.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_5.setFont(font)
        self.l_3_5.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_5.setObjectName("l_3_5")
        self.l2_3_5 = QtWidgets.QLabel(self._3_5)
        self.l2_3_5.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_5.setText("")
        self.l2_3_5.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_5.setScaledContents(True)
        self.l2_3_5.setObjectName("l2_3_5")
        self.verticalLayout_2.addWidget(self._3_5)
        self._3_6 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_6.setObjectName("_3_6")
        self.l_3_6 = QtWidgets.QLabel(self._3_6)
        self.l_3_6.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_6.setFont(font)
        self.l_3_6.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_6.setObjectName("l_3_6")
        self.l2_3_6 = QtWidgets.QLabel(self._3_6)
        self.l2_3_6.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_6.setText("")
        self.l2_3_6.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_6.setScaledContents(True)
        self.l2_3_6.setObjectName("l2_3_6")
        self.verticalLayout_2.addWidget(self._3_6)
        self._3_7 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_7.setObjectName("_3_7")
        self.l_3_7 = QtWidgets.QLabel(self._3_7)
        self.l_3_7.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_7.setFont(font)
        self.l_3_7.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_7.setObjectName("l_3_7")
        self.l2_3_7 = QtWidgets.QLabel(self._3_7)
        self.l2_3_7.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_7.setText("")
        self.l2_3_7.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_7.setScaledContents(True)
        self.l2_3_7.setObjectName("l2_3_7")
        self.verticalLayout_2.addWidget(self._3_7)
        self._3_8 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_8.setObjectName("_3_8")
        self.l_3_8 = QtWidgets.QLabel(self._3_8)
        self.l_3_8.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_8.setFont(font)
        self.l_3_8.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_8.setObjectName("l_3_8")
        self.l2_3_8 = QtWidgets.QLabel(self._3_8)
        self.l2_3_8.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_8.setText("")
        self.l2_3_8.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_8.setScaledContents(True)
        self.l2_3_8.setObjectName("l2_3_8")
        self.verticalLayout_2.addWidget(self._3_8)
        self._3_9 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_9.setObjectName("_3_9")
        self.l_3_9 = QtWidgets.QLabel(self._3_9)
        self.l_3_9.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_9.setFont(font)
        self.l_3_9.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_9.setObjectName("l_3_9")
        self.l2_3_9 = QtWidgets.QLabel(self._3_9)
        self.l2_3_9.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_9.setText("")
        self.l2_3_9.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_9.setScaledContents(True)
        self.l2_3_9.setObjectName("l2_3_9")
        self.verticalLayout_2.addWidget(self._3_9)
        self._3_10 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_10.setObjectName("_3_10")
        self.l_3_10 = QtWidgets.QLabel(self._3_10)
        self.l_3_10.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_10.setFont(font)
        self.l_3_10.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_10.setObjectName("l_3_10")
        self.l2_3_10 = QtWidgets.QLabel(self._3_10)
        self.l2_3_10.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_10.setText("")
        self.l2_3_10.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_10.setScaledContents(True)
        self.l2_3_10.setObjectName("l2_3_10")
        self.verticalLayout_2.addWidget(self._3_10)
        self._3_11 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_11.setObjectName("_3_11")
        self.l_3_11 = QtWidgets.QLabel(self._3_11)
        self.l_3_11.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_11.setFont(font)
        self.l_3_11.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_11.setObjectName("l_3_11")
        self.l2_3_11 = QtWidgets.QLabel(self._3_11)
        self.l2_3_11.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_11.setText("")
        self.l2_3_11.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_11.setScaledContents(True)
        self.l2_3_11.setObjectName("l2_3_11")
        self.verticalLayout_2.addWidget(self._3_11)
        self._3_12 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_12.setObjectName("_3_12")
        self.l_3_12 = QtWidgets.QLabel(self._3_12)
        self.l_3_12.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_12.setFont(font)
        self.l_3_12.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_12.setObjectName("l_3_12")
        self.l2_3_12 = QtWidgets.QLabel(self._3_12)
        self.l2_3_12.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_12.setText("")
        self.l2_3_12.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_12.setScaledContents(True)
        self.l2_3_12.setObjectName("l2_3_12")
        self.verticalLayout_2.addWidget(self._3_12)
        self._3_13 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_13.setObjectName("_3_13")
        self.l_3_13 = QtWidgets.QLabel(self._3_13)
        self.l_3_13.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_13.setFont(font)
        self.l_3_13.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_13.setObjectName("l_3_13")
        self.l2_3_13 = QtWidgets.QLabel(self._3_13)
        self.l2_3_13.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_13.setText("")
        self.l2_3_13.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_13.setScaledContents(True)
        self.l2_3_13.setObjectName("l2_3_13")
        self.verticalLayout_2.addWidget(self._3_13)
        self._3_14 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_14.setObjectName("_3_14")
        self.l_3_14 = QtWidgets.QLabel(self._3_14)
        self.l_3_14.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_14.setFont(font)
        self.l_3_14.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_14.setObjectName("l_3_14")
        self.l2_3_14 = QtWidgets.QLabel(self._3_14)
        self.l2_3_14.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_14.setText("")
        self.l2_3_14.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_14.setScaledContents(True)
        self.l2_3_14.setObjectName("l2_3_14")
        self.verticalLayout_2.addWidget(self._3_14)
        self._3_15 = QtWidgets.QWidget(self.verticalLayoutWidget_4)
        self._3_15.setObjectName("_3_15")
        self.l_3_15 = QtWidgets.QLabel(self._3_15)
        self.l_3_15.setGeometry(QtCore.QRect(20, 0, 441, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.l_3_15.setFont(font)
        self.l_3_15.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.l_3_15.setObjectName("l_3_15")
        self.l2_3_15 = QtWidgets.QLabel(self._3_15)
        self.l2_3_15.setGeometry(QtCore.QRect(465, 17, 15, 25))
        self.l2_3_15.setText("")
        self.l2_3_15.setPixmap(QtGui.QPixmap("image/right.png"))
        self.l2_3_15.setScaledContents(True)
        self.l2_3_15.setObjectName("l2_3_15")
        self.verticalLayout_2.addWidget(self._3_15)
        self.trash_con_5 = QtWidgets.QLabel(self.set_trash_change)
        self.trash_con_5.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con_5.setFont(font)
        self.trash_con_5.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_5.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_5.setObjectName("trash_con_5")
        self.tabWidget.addTab(self.set_trash_change, "")
        self.set_credit = QtWidgets.QWidget()
        self.set_credit.setObjectName("set_credit")
        self.trash_set_title_9 = QtWidgets.QLabel(self.set_credit)
        self.trash_set_title_9.setGeometry(QtCore.QRect(0, 0, 501, 81))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.trash_set_title_9.setFont(font)
        self.trash_set_title_9.setStyleSheet("color : rgb(255,255,255);\n"
"background-color: rgb(0,139,188);\n"
"")
        self.trash_set_title_9.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_set_title_9.setObjectName("trash_set_title_9")
        self.trash_con_9 = QtWidgets.QLabel(self.set_credit)
        self.trash_con_9.setGeometry(QtCore.QRect(0, 1040, 501, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(22)
        self.trash_con_9.setFont(font)
        self.trash_con_9.setStyleSheet("color : rgb(255,255,255)")
        self.trash_con_9.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_con_9.setObjectName("trash_con_9")
        self.label_6 = QtWidgets.QLabel(self.set_credit)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 451, 561))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("image/credit.png"))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.set_credit, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 0, 21, 1081))
        self.label.setObjectName("label")
        self.next_title = QtWidgets.QLabel(self.centralwidget)
        self.next_title.setGeometry(QtCore.QRect(1460, 20, 461, 71))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.next_title.setFont(font)
        self.next_title.setStyleSheet("color : rgb(200,200,200);\n"
"")
        self.next_title.setAlignment(QtCore.Qt.AlignCenter)
        self.next_title.setObjectName("next_title")
        self.next_menu = QtWidgets.QLabel(self.centralwidget)
        self.next_menu.setGeometry(QtCore.QRect(1460, 110, 461, 801))
        font = QtGui.QFont()
        font.setFamily("배달의민족 도현")
        font.setPointSize(36)
        self.next_menu.setFont(font)
        self.next_menu.setMouseTracking(True)
        self.next_menu.setStyleSheet("color : rgb(225,225,225);")
        self.next_menu.setTextFormat(QtCore.Qt.AutoText)
        self.next_menu.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.next_menu.setWordWrap(True)
        self.next_menu.setObjectName("next_menu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.trash_menu.setText(_translate("MainWindow", "<html><head/><body><p>달걀껍질</p><p>닭 뼈</p><p>양파껍질</p></body></html>"))
        self.trash_title.setText(_translate("MainWindow", "-일반쓰레기-"))
        self.trash_day.setText(_translate("MainWindow", "YYYY년 MM월 DD일(조식)"))
        self.trash_school.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.trash_set_title.setText(_translate("MainWindow", "설정"))
        self.trash_con.setText(_translate("MainWindow", "▲/▼ : 이동   ▶/▣ : 확인   ◀ : 나가기"))
        self.label_3.setText(_translate("MainWindow", "학교설정"))
        self.label_17.setText(_translate("MainWindow", "급식 시간 설정"))
        self.label_21.setText(_translate("MainWindow", "일반 쓰레기 수정"))
        self.label_55.setText(_translate("MainWindow", "크레딧"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_main), _translate("MainWindow", "Tab 1"))
        self.set_kit_1_title.setText(_translate("MainWindow", "15개 이하"))
        self.trash_con_3.setText(_translate("MainWindow", "▲/▼ : 이동   ▶/▣ : 확인   ◀ : 나가기"))
        self.l1.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l2.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l3.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l4.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l5.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l6.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l7.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l8.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l9.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l10.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l11.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l12.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l13.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l14.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l15.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_kit_1_1), _translate("MainWindow", "Page"))
        self.set_kit_2_title.setText(_translate("MainWindow", "16개 이상"))
        self.trash_con_4.setText(_translate("MainWindow", "▲/▼ : 이동   ▶/▣ : 확인   ◀ : 나가기"))
        self.l21.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l22.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l23.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l24.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l25.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l26.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l27.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l28.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l29.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l210.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l211.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l212.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l213.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l214.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.trash_con_6.setText(_translate("MainWindow", "▼"))
        self.trash_con_7.setText(_translate("MainWindow", "▲"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_sc_2_2), _translate("MainWindow", "Page"))
        self.trash_set_title_8.setText(_translate("MainWindow", "급식시간"))
        self.trash_con_8.setText(_translate("MainWindow", "▲/▼ : 이동  ▶/▣ : 확인  ◀ : 나가기"))
        self.label_15.setText(_translate("MainWindow", "조식"))
        self.label_24.setText(_translate("MainWindow", "중식"))
        self.label_26.setText(_translate("MainWindow", "석식"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_eat_time), _translate("MainWindow", "Page"))
        self.trash_con_10.setText(_translate("MainWindow", "▲/▼ : 시   ◀/▶ : 분   ▣ : 확인"))
        self.set_time_change_title.setText(_translate("MainWindow", "OO종료시간"))
        self.set_time_change_value.setText(_translate("MainWindow", "MM:SS"))
        self.trash_con_11.setText(_translate("MainWindow", "※시작시간이 아닌 종료시간을 입력해 주세요"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_time_change), _translate("MainWindow", "Page"))
        self.trash_set_title_5.setText(_translate("MainWindow", "일반 쓰레기 설정"))
        self.l_3_1.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_2.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_3.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_4.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_5.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_6.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_7.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_8.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_9.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_10.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_11.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_12.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_13.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_14.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.l_3_15.setText(_translate("MainWindow", "대구소프트웨어고등학교"))
        self.trash_con_5.setText(_translate("MainWindow", "▲/▼ : 이동   ▶/▣ : 확인   ◀ : 나가기"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_trash_change), _translate("MainWindow", "Page"))
        self.trash_set_title_9.setText(_translate("MainWindow", "크레딧"))
        self.trash_con_9.setText(_translate("MainWindow", "▲/▼/◀/▶/▣ : 나가기"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.set_credit), _translate("MainWindow", "Page"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.next_title.setText(_translate("MainWindow", "-다음 급식-"))
        self.next_menu.setText(_translate("MainWindow", "현미밥\n"
"강된장찌개\n"
"시리얼초코우유ㄴㅇㄹㄴㅇㄹ\n"
"상추쌈\n"
"쌈장\n"
"배추김치\n"
"감귤"))

