# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\bus_info\gui\design.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color : rgb(0, 0, 0)")
        self.centralwidget.setObjectName("centralwidget")
        self.imgPanel = QtWidgets.QLabel(self.centralwidget)
        self.imgPanel.setGeometry(QtCore.QRect(0, 0, 763, 1080))
        self.imgPanel.setObjectName("imgPanel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(790, 925, 141, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 960, 1101, 20))
        self.label_2.setStyleSheet("border-bottom : 3px solid rgb(255,255,255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.now_num = QtWidgets.QLabel(self.centralwidget)
        self.now_num.setGeometry(QtCore.QRect(790, 1000, 1101, 61))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.now_num.setFont(font)
        self.now_num.setStyleSheet("color:rgb(255,255,255)")
        self.now_num.setScaledContents(False)
        self.now_num.setWordWrap(True)
        self.now_num.setObjectName("now_num")
        self.bus_num = QtWidgets.QLabel(self.centralwidget)
        self.bus_num.setGeometry(QtCore.QRect(760, 90, 371, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bus_num.sizePolicy().hasHeightForWidth())
        self.bus_num.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.bus_num.setFont(font)
        self.bus_num.setStyleSheet("color:rgb(255,255,255);\n"
"line-height:1%")
        self.bus_num.setScaledContents(False)
        self.bus_num.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.bus_num.setWordWrap(False)
        self.bus_num.setOpenExternalLinks(False)
        self.bus_num.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bus_num.setObjectName("bus_num")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(865, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.label_3.setObjectName("label_3")
        self.bus_time = QtWidgets.QLabel(self.centralwidget)
        self.bus_time.setGeometry(QtCore.QRect(1140, 90, 231, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bus_time.sizePolicy().hasHeightForWidth())
        self.bus_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.bus_time.setFont(font)
        self.bus_time.setStyleSheet("color:rgb(255,255,255);\n"
"line-height:1%")
        self.bus_time.setScaledContents(False)
        self.bus_time.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.bus_time.setWordWrap(False)
        self.bus_time.setOpenExternalLinks(False)
        self.bus_time.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bus_time.setObjectName("bus_time")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1175, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(32)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1560, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(32)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color : rgb(255,255,255)\n"
"")
        self.label_5.setObjectName("label_5")
        self.bus_nolo = QtWidgets.QLabel(self.centralwidget)
        self.bus_nolo.setGeometry(QtCore.QRect(1370, 130, 541, 751))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bus_nolo.sizePolicy().hasHeightForWidth())
        self.bus_nolo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어라운드 Bold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.bus_nolo.setFont(font)
        self.bus_nolo.setStyleSheet("color:rgb(255,255,255);\n"
"line-height:1%")
        self.bus_nolo.setScaledContents(False)
        self.bus_nolo.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.bus_nolo.setWordWrap(False)
        self.bus_nolo.setOpenExternalLinks(False)
        self.bus_nolo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.bus_nolo.setObjectName("bus_nolo")
        self.bus_nolo.raise_()
        self.imgPanel.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.now_num.raise_()
        self.label_3.raise_()
        self.bus_time.raise_()
        self.bus_num.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.imgPanel.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "잠시후"))
        self.now_num.setText(_translate("MainWindow", "111  222  333  555-1  1242  12  513 1234"))
        self.bus_num.setText(_translate("MainWindow", "<html><head/><body><p style=\"line-height:1.15\"><span>312<br>53<br>1237<br>536-1<br>243<br>1234-1</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "노선번호"))
        self.bus_time.setText(_translate("MainWindow", "<html><head/><body><p style=\"line-height:1.15\"><span>2분<br>3분<br>12분<br>30분<br>15분<br>1분</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "도착예정"))
        self.label_5.setText(_translate("MainWindow", "현재위치"))
        self.bus_nolo.setText(_translate("MainWindow", "<html><head/><body><p style=\"line-height:2.57\"><span>가나다라마바사(5전)\n"
"<br>가나다라마바사(5전)\n"
"<br>가나다라마바사(5전)\n"
"<br>가나다라마바사(5전)\n"
"<br>가나다라마바사(5전)\n"
"<br>가나다라마바사(5전)\n"
"<br></span></p></body></html>"))
